modLoader="javafml"
license="All Rights Reserved"
loaderVersion="[41,)"
issueTrackerURL="https://github.com/Glitchfiend/SereneSeasons/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/serene-seasons"
logoFile="ss_logo.png"

[[mods]]
    modId="sereneseasons"
    version="${file.jarVersion}"
    displayName="Serene Seasons"
	authors="Adubbz, Forstride"
    description="Adds seasons with changing colors, temperature shifting, and more!"

[[dependencies.sereneseasons]]
    modId="forge"
    mandatory=true
    versionRange="[41.0.64,)"
    ordering="NONE"
    side="BOTH"